services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/witelokk/music-api:latest
    container_name: music-api
    profiles:
      - local
      - prod
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      DATABASE_URL: postgres://music_user:music_password@postgres:5432/music_db?sslmode=disable
      REDIS_URL: redis:6379
    depends_on:
      - postgres
      - redis
    ports:
      - "80:8080"
    networks:
      - backend

  postgres:
    image: postgres:16-alpine
    container_name: music-postgres
    profiles:
      - local
    environment:
      POSTGRES_DB: music_db
      POSTGRES_USER: music_user
      POSTGRES_PASSWORD: music_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: music-redis
    profiles:
      - local
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
    driver: bridge
