services:
  music-api:
    image: ghcr.io/witelokk/music-api:main
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://music-api_postgres/"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "postgres"
      REDIS_URL: "music-api_redis:6379"
      JWT_SECRET: ${JWT_SECRET}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      MAILGUN_FROM: ${MAILGUN_FROM}
      GOOGLE_AUTH_AUDIENCE: ${GOOGLE_AUTH_AUDIENCE}
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: unless-stopped
  nginx:
    image: ghcr.io/max-lt/nginx-jwt-module:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
      - source: jwt_key
        target: /etc/nginx/jwt_key
    volumes:
      - content:/var/www/files:ro
    depends_on:
      - music-api

configs:
  nginx_conf:
    file: ./nginx.conf
  jwt_key:
    file: ./local/jwt_key

volumes:
  postgres_data:
  content: