services:
  music-api:
    build: .
    environment:
      DATABASE_URL: "postgresql://postgres/"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "postgres"
      REDIS_URL: "redis:5432"
      JWT_SECRET: ${JWT_SECRET}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      MAILGUN_FROM: ${MAILGUN_FROM}
      GOOGLE_AUTH_AUDIENCE: ${GOOGLE_AUTH_AUDIENCE}
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379"
  nginx:
    image: ghcr.io/max-lt/nginx-jwt-module:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./local/jwt_key:/etc/nginx/jwt_key:ro
      - ./local/content:/var/www/files:ro
    depends_on:
      - music-api

volumes:
  postgres_data: