ktor:
    application:
        modules:
            - com.witelokk.ApplicationKt.module
    deployment:
        port: 8080

database:
    url: $DATABASE_URL
    user: $DATABASE_USER
    password: $DATABASE_PASSWORD

redis:
    url: $REDIS_URL

jwt:
    secret: $JWT_SECRET

mailgun:
    api_key: $MAILGUN_API_KEY
    domain: $MAILGUN_DOMAIN
    from: $MAILGUN_FROM

google-auth:
    audience: $GOOGLE_AUTH_AUDIENCE
