DROP TABLE IF EXISTS playlist_songs;
DROP TABLE IF EXISTS playlists;
DROP TABLE IF EXISTS followings;
DROP TABLE IF EXISTS favorites;
DROP TABLE IF EXISTS release_songs;
DROP TABLE IF EXISTS song_artists;
DROP TABLE IF EXISTS releases;
DROP TABLE IF EXISTS artists;
DROP TABLE IF EXISTS songs;
DROP TABLE IF EXISTS users;

DROP EXTENSION IF EXISTS "pgcrypto";

