//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapi

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for GetTokensRequestGrantType.
const (
	Code         GetTokensRequestGrantType = "code"
	RefreshToken GetTokensRequestGrantType = "refresh_token"
)

// Valid indicates whether the value is a known member of the GetTokensRequestGrantType enum.
func (e GetTokensRequestGrantType) Valid() bool {
	switch e {
	case Code:
		return true
	case RefreshToken:
		return true
	default:
		return false
	}
}

// AddSongToPlaylistRequest defines model for AddSongToPlaylistRequest.
type AddSongToPlaylistRequest struct {
	SongId openapi_types.UUID `json:"song_id"`
}

// Artist defines model for Artist.
type Artist struct {
	AvatarUrl    *string            `json:"avatar_url,omitempty"`
	CoverUrl     *string            `json:"cover_url,omitempty"`
	Followers    int                `json:"followers"`
	Following    bool               `json:"following"`
	Id           openapi_types.UUID `json:"id"`
	Name         string             `json:"name"`
	PopularSongs SongList           `json:"popularSongs"`
	Releases     ReleaseList        `json:"releases"`
}

// ArtistList defines model for ArtistList.
type ArtistList struct {
	Artists []ArtistSummary `json:"artists"`
	Count   int             `json:"count"`
	Names   string          `json:"names"`
}

// ArtistSummary defines model for ArtistSummary.
type ArtistSummary struct {
	AvatarUrl *string            `json:"avatar_url,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
}

// CreatePlaylistRequest defines model for CreatePlaylistRequest.
type CreatePlaylistRequest struct {
	Name string `json:"name"`
}

// CreatePlaylistResponse defines model for CreatePlaylistResponse.
type CreatePlaylistResponse struct {
	Id openapi_types.UUID `json:"id"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	// Code Verification code received by email.
	Code string `json:"code"`

	// Email User's email address.
	Email openapi_types.Email `json:"email"`

	// Name User's display name.
	Name string `json:"name"`
}

// CurrentUser defines model for CurrentUser.
type CurrentUser struct {
	Email openapi_types.Email `json:"email"`
	Name  string              `json:"name"`
}

// Error defines model for Error.
type Error struct {
	// Error Human-readable error message.
	Error string `json:"error"`
}

// FavoriteSongRequest defines model for FavoriteSongRequest.
type FavoriteSongRequest struct {
	SongId openapi_types.UUID `json:"song_id"`
}

// FollowArtistRequest defines model for FollowArtistRequest.
type FollowArtistRequest struct {
	ArtistId openapi_types.UUID `json:"artist_id"`
}

// GetTokensRequest Request to obtain tokens.
// - For `grant_type` = `code`, `email` and `code` are required.
// - For `grant_type` = `refresh_token`, `refresh_token` is required.
type GetTokensRequest struct {
	// Code Verification code, required with `grant_type` = `code`.
	Code *string `json:"code,omitempty"`

	// Email User email, required with `grant_type` = `code`.
	Email *openapi_types.Email `json:"email,omitempty"`

	// GoogleToken Reserved for future Google auth integration.
	GoogleToken *string `json:"google_token,omitempty"`

	// GrantType Grant type to use.
	GrantType GetTokensRequestGrantType `json:"grant_type"`

	// RefreshToken Refresh token, required with `grant_type` = `refresh_token`.
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// GetTokensRequestGrantType Grant type to use.
type GetTokensRequestGrantType string

// Playlist defines model for Playlist.
type Playlist struct {
	CoverUrl   *string            `json:"cover_url,omitempty"`
	Id         openapi_types.UUID `json:"id"`
	Name       string             `json:"name"`
	Songs      SongList           `json:"songs"`
	SongsCount int                `json:"songs_count"`
}

// PlaylistSummary defines model for PlaylistSummary.
type PlaylistSummary struct {
	CoverUrl   *string            `json:"cover_url,omitempty"`
	Id         openapi_types.UUID `json:"id"`
	Name       string             `json:"name"`
	SongsCount int                `json:"songs_count"`
}

// PlaylistsSummary defines model for PlaylistsSummary.
type PlaylistsSummary struct {
	Count     int               `json:"count"`
	Playlists []PlaylistSummary `json:"playlists"`
}

// Release defines model for Release.
type Release struct {
	Artists    ArtistList         `json:"artists"`
	CoverUrl   *string            `json:"cover_url,omitempty"`
	Id         openapi_types.UUID `json:"id"`
	Name       string             `json:"name"`
	ReleasedAt string             `json:"released_at"`
	Songs      SongList           `json:"songs"`
	Type       string             `json:"type"`
}

// ReleaseList defines model for ReleaseList.
type ReleaseList struct {
	Count    int       `json:"count"`
	Releases []Release `json:"releases"`
}

// RemoveSongFromPlaylistRequest defines model for RemoveSongFromPlaylistRequest.
type RemoveSongFromPlaylistRequest struct {
	SongId openapi_types.UUID `json:"song_id"`
}

// SendVerificationEmailRequest defines model for SendVerificationEmailRequest.
type SendVerificationEmailRequest struct {
	// Email Email address to send a verification code to.
	Email openapi_types.Email `json:"email"`
}

// Song defines model for Song.
type Song struct {
	Artists         []ArtistSummary    `json:"artists"`
	CoverUrl        *string            `json:"cover_url,omitempty"`
	DurationSeconds int                `json:"duration_seconds"`
	Id              openapi_types.UUID `json:"id"`
	IsFavorite      bool               `json:"is_favorite"`
	Name            string             `json:"name"`
	StreamUrl       string             `json:"stream_url"`
}

// SongList defines model for SongList.
type SongList struct {
	Count int    `json:"count"`
	Songs []Song `json:"songs"`
}

// TokensResponse defines model for TokensResponse.
type TokensResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// UpdatePlaylistRequest defines model for UpdatePlaylistRequest.
type UpdatePlaylistRequest struct {
	Name string `json:"name"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`
	Name      string              `json:"name"`
}

// RemoveFavoriteJSONRequestBody defines body for RemoveFavorite for application/json ContentType.
type RemoveFavoriteJSONRequestBody = FavoriteSongRequest

// AddFavoriteJSONRequestBody defines body for AddFavorite for application/json ContentType.
type AddFavoriteJSONRequestBody = FavoriteSongRequest

// UnfollowArtistJSONRequestBody defines body for UnfollowArtist for application/json ContentType.
type UnfollowArtistJSONRequestBody = FollowArtistRequest

// FollowArtistJSONRequestBody defines body for FollowArtist for application/json ContentType.
type FollowArtistJSONRequestBody = FollowArtistRequest

// CreatePlaylistJSONRequestBody defines body for CreatePlaylist for application/json ContentType.
type CreatePlaylistJSONRequestBody = CreatePlaylistRequest

// UpdatePlaylistJSONRequestBody defines body for UpdatePlaylist for application/json ContentType.
type UpdatePlaylistJSONRequestBody = UpdatePlaylistRequest

// RemoveSongFromPlaylistJSONRequestBody defines body for RemoveSongFromPlaylist for application/json ContentType.
type RemoveSongFromPlaylistJSONRequestBody = RemoveSongFromPlaylistRequest

// AddSongToPlaylistJSONRequestBody defines body for AddSongToPlaylist for application/json ContentType.
type AddSongToPlaylistJSONRequestBody = AddSongToPlaylistRequest

// GenerateTokensJSONRequestBody defines body for GenerateTokens for application/json ContentType.
type GenerateTokensJSONRequestBody = GetTokensRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// SendVerificationEmailJSONRequestBody defines body for SendVerificationEmail for application/json ContentType.
type SendVerificationEmailJSONRequestBody = SendVerificationEmailRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get artist by ID
	// (GET /artists/{id})
	GetArtist(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Remove song from favorites
	// (DELETE /favorites)
	RemoveFavorite(w http.ResponseWriter, r *http.Request)
	// Get favorite songs
	// (GET /favorites)
	GetFavorites(w http.ResponseWriter, r *http.Request)
	// Add song to favorites
	// (POST /favorites)
	AddFavorite(w http.ResponseWriter, r *http.Request)
	// Unfollow an artist
	// (DELETE /followings)
	UnfollowArtist(w http.ResponseWriter, r *http.Request)
	// Get followed artists
	// (GET /followings)
	GetFollowings(w http.ResponseWriter, r *http.Request)
	// Follow an artist
	// (POST /followings)
	FollowArtist(w http.ResponseWriter, r *http.Request)
	// Get media file
	// (GET /media/{id})
	GetMedia(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get a list of playlists
	// (GET /playlists)
	GetPlaylists(w http.ResponseWriter, r *http.Request)
	// Create a new playlist
	// (POST /playlists)
	CreatePlaylist(w http.ResponseWriter, r *http.Request)
	// Delete a playlist
	// (DELETE /playlists/{id})
	DeletePlaylist(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get playlist by ID
	// (GET /playlists/{id})
	GetPlaylist(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update a playlist
	// (PUT /playlists/{id})
	UpdatePlaylist(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Remove song from playlist
	// (DELETE /playlists/{id}/songs)
	RemoveSongFromPlaylist(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get playlist songs
	// (GET /playlists/{id}/songs)
	GetPlaylistSongs(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Add song to playlist
	// (POST /playlists/{id}/songs)
	AddSongToPlaylist(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get release by ID
	// (GET /releases/{id})
	GetRelease(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get song by ID
	// (GET /songs/{id})
	GetSong(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Obtain access and refresh tokens
	// (POST /tokens)
	GenerateTokens(w http.ResponseWriter, r *http.Request)
	// Create user with verification code
	// (POST /users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// Get current authenticated user
	// (GET /users/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// Send verification email
	// (POST /verification-email)
	SendVerificationEmail(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetArtist operation middleware
func (siw *ServerInterfaceWrapper) GetArtist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArtist(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveFavorite operation middleware
func (siw *ServerInterfaceWrapper) RemoveFavorite(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveFavorite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFavorites operation middleware
func (siw *ServerInterfaceWrapper) GetFavorites(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFavorites(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddFavorite operation middleware
func (siw *ServerInterfaceWrapper) AddFavorite(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddFavorite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnfollowArtist operation middleware
func (siw *ServerInterfaceWrapper) UnfollowArtist(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnfollowArtist(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFollowings operation middleware
func (siw *ServerInterfaceWrapper) GetFollowings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFollowings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FollowArtist operation middleware
func (siw *ServerInterfaceWrapper) FollowArtist(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FollowArtist(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMedia operation middleware
func (siw *ServerInterfaceWrapper) GetMedia(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMedia(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlaylists operation middleware
func (siw *ServerInterfaceWrapper) GetPlaylists(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlaylists(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePlaylist operation middleware
func (siw *ServerInterfaceWrapper) CreatePlaylist(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePlaylist(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePlaylist operation middleware
func (siw *ServerInterfaceWrapper) DeletePlaylist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePlaylist(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlaylist operation middleware
func (siw *ServerInterfaceWrapper) GetPlaylist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlaylist(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePlaylist operation middleware
func (siw *ServerInterfaceWrapper) UpdatePlaylist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePlaylist(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveSongFromPlaylist operation middleware
func (siw *ServerInterfaceWrapper) RemoveSongFromPlaylist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveSongFromPlaylist(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlaylistSongs operation middleware
func (siw *ServerInterfaceWrapper) GetPlaylistSongs(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlaylistSongs(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddSongToPlaylist operation middleware
func (siw *ServerInterfaceWrapper) AddSongToPlaylist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddSongToPlaylist(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRelease operation middleware
func (siw *ServerInterfaceWrapper) GetRelease(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRelease(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSong operation middleware
func (siw *ServerInterfaceWrapper) GetSong(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSong(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateTokens operation middleware
func (siw *ServerInterfaceWrapper) GenerateTokens(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateTokens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendVerificationEmail operation middleware
func (siw *ServerInterfaceWrapper) SendVerificationEmail(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendVerificationEmail(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/artists/{id}", wrapper.GetArtist)
	m.HandleFunc("DELETE "+options.BaseURL+"/favorites", wrapper.RemoveFavorite)
	m.HandleFunc("GET "+options.BaseURL+"/favorites", wrapper.GetFavorites)
	m.HandleFunc("POST "+options.BaseURL+"/favorites", wrapper.AddFavorite)
	m.HandleFunc("DELETE "+options.BaseURL+"/followings", wrapper.UnfollowArtist)
	m.HandleFunc("GET "+options.BaseURL+"/followings", wrapper.GetFollowings)
	m.HandleFunc("POST "+options.BaseURL+"/followings", wrapper.FollowArtist)
	m.HandleFunc("GET "+options.BaseURL+"/media/{id}", wrapper.GetMedia)
	m.HandleFunc("GET "+options.BaseURL+"/playlists", wrapper.GetPlaylists)
	m.HandleFunc("POST "+options.BaseURL+"/playlists", wrapper.CreatePlaylist)
	m.HandleFunc("DELETE "+options.BaseURL+"/playlists/{id}", wrapper.DeletePlaylist)
	m.HandleFunc("GET "+options.BaseURL+"/playlists/{id}", wrapper.GetPlaylist)
	m.HandleFunc("PUT "+options.BaseURL+"/playlists/{id}", wrapper.UpdatePlaylist)
	m.HandleFunc("DELETE "+options.BaseURL+"/playlists/{id}/songs", wrapper.RemoveSongFromPlaylist)
	m.HandleFunc("GET "+options.BaseURL+"/playlists/{id}/songs", wrapper.GetPlaylistSongs)
	m.HandleFunc("POST "+options.BaseURL+"/playlists/{id}/songs", wrapper.AddSongToPlaylist)
	m.HandleFunc("GET "+options.BaseURL+"/releases/{id}", wrapper.GetRelease)
	m.HandleFunc("GET "+options.BaseURL+"/songs/{id}", wrapper.GetSong)
	m.HandleFunc("POST "+options.BaseURL+"/tokens", wrapper.GenerateTokens)
	m.HandleFunc("POST "+options.BaseURL+"/users", wrapper.CreateUser)
	m.HandleFunc("GET "+options.BaseURL+"/users/me", wrapper.GetCurrentUser)
	m.HandleFunc("POST "+options.BaseURL+"/verification-email", wrapper.SendVerificationEmail)

	return m
}

type GetArtistRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetArtistResponseObject interface {
	VisitGetArtistResponse(w http.ResponseWriter) error
}

type GetArtist200JSONResponse Artist

func (response GetArtist200JSONResponse) VisitGetArtistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetArtist404JSONResponse Error

func (response GetArtist404JSONResponse) VisitGetArtistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetArtist500JSONResponse Error

func (response GetArtist500JSONResponse) VisitGetArtistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RemoveFavoriteRequestObject struct {
	Body *RemoveFavoriteJSONRequestBody
}

type RemoveFavoriteResponseObject interface {
	VisitRemoveFavoriteResponse(w http.ResponseWriter) error
}

type RemoveFavorite204Response struct {
}

func (response RemoveFavorite204Response) VisitRemoveFavoriteResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RemoveFavorite400JSONResponse Error

func (response RemoveFavorite400JSONResponse) VisitRemoveFavoriteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RemoveFavorite404JSONResponse Error

func (response RemoveFavorite404JSONResponse) VisitRemoveFavoriteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RemoveFavorite500JSONResponse Error

func (response RemoveFavorite500JSONResponse) VisitRemoveFavoriteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetFavoritesRequestObject struct {
}

type GetFavoritesResponseObject interface {
	VisitGetFavoritesResponse(w http.ResponseWriter) error
}

type GetFavorites200JSONResponse SongList

func (response GetFavorites200JSONResponse) VisitGetFavoritesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetFavorites500JSONResponse Error

func (response GetFavorites500JSONResponse) VisitGetFavoritesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddFavoriteRequestObject struct {
	Body *AddFavoriteJSONRequestBody
}

type AddFavoriteResponseObject interface {
	VisitAddFavoriteResponse(w http.ResponseWriter) error
}

type AddFavorite204Response struct {
}

func (response AddFavorite204Response) VisitAddFavoriteResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type AddFavorite400JSONResponse Error

func (response AddFavorite400JSONResponse) VisitAddFavoriteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddFavorite404JSONResponse Error

func (response AddFavorite404JSONResponse) VisitAddFavoriteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AddFavorite500JSONResponse Error

func (response AddFavorite500JSONResponse) VisitAddFavoriteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UnfollowArtistRequestObject struct {
	Body *UnfollowArtistJSONRequestBody
}

type UnfollowArtistResponseObject interface {
	VisitUnfollowArtistResponse(w http.ResponseWriter) error
}

type UnfollowArtist204Response struct {
}

func (response UnfollowArtist204Response) VisitUnfollowArtistResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UnfollowArtist400JSONResponse Error

func (response UnfollowArtist400JSONResponse) VisitUnfollowArtistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UnfollowArtist404JSONResponse Error

func (response UnfollowArtist404JSONResponse) VisitUnfollowArtistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UnfollowArtist500JSONResponse Error

func (response UnfollowArtist500JSONResponse) VisitUnfollowArtistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetFollowingsRequestObject struct {
}

type GetFollowingsResponseObject interface {
	VisitGetFollowingsResponse(w http.ResponseWriter) error
}

type GetFollowings200JSONResponse ArtistList

func (response GetFollowings200JSONResponse) VisitGetFollowingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetFollowings500JSONResponse Error

func (response GetFollowings500JSONResponse) VisitGetFollowingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type FollowArtistRequestObject struct {
	Body *FollowArtistJSONRequestBody
}

type FollowArtistResponseObject interface {
	VisitFollowArtistResponse(w http.ResponseWriter) error
}

type FollowArtist204Response struct {
}

func (response FollowArtist204Response) VisitFollowArtistResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type FollowArtist400JSONResponse Error

func (response FollowArtist400JSONResponse) VisitFollowArtistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type FollowArtist404JSONResponse Error

func (response FollowArtist404JSONResponse) VisitFollowArtistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type FollowArtist500JSONResponse Error

func (response FollowArtist500JSONResponse) VisitFollowArtistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetMediaRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetMediaResponseObject interface {
	VisitGetMediaResponse(w http.ResponseWriter) error
}

type GetMedia200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetMedia200ApplicationoctetStreamResponse) VisitGetMediaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetMedia404JSONResponse Error

func (response GetMedia404JSONResponse) VisitGetMediaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetMedia500JSONResponse Error

func (response GetMedia500JSONResponse) VisitGetMediaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetPlaylistsRequestObject struct {
}

type GetPlaylistsResponseObject interface {
	VisitGetPlaylistsResponse(w http.ResponseWriter) error
}

type GetPlaylists200JSONResponse PlaylistsSummary

func (response GetPlaylists200JSONResponse) VisitGetPlaylistsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPlaylists500JSONResponse Error

func (response GetPlaylists500JSONResponse) VisitGetPlaylistsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreatePlaylistRequestObject struct {
	Body *CreatePlaylistJSONRequestBody
}

type CreatePlaylistResponseObject interface {
	VisitCreatePlaylistResponse(w http.ResponseWriter) error
}

type CreatePlaylist201JSONResponse CreatePlaylistResponse

func (response CreatePlaylist201JSONResponse) VisitCreatePlaylistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreatePlaylist400JSONResponse Error

func (response CreatePlaylist400JSONResponse) VisitCreatePlaylistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreatePlaylist500JSONResponse Error

func (response CreatePlaylist500JSONResponse) VisitCreatePlaylistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeletePlaylistRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeletePlaylistResponseObject interface {
	VisitDeletePlaylistResponse(w http.ResponseWriter) error
}

type DeletePlaylist204Response struct {
}

func (response DeletePlaylist204Response) VisitDeletePlaylistResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeletePlaylist404JSONResponse Error

func (response DeletePlaylist404JSONResponse) VisitDeletePlaylistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeletePlaylist500JSONResponse Error

func (response DeletePlaylist500JSONResponse) VisitDeletePlaylistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetPlaylistRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetPlaylistResponseObject interface {
	VisitGetPlaylistResponse(w http.ResponseWriter) error
}

type GetPlaylist200JSONResponse Playlist

func (response GetPlaylist200JSONResponse) VisitGetPlaylistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPlaylist404JSONResponse Error

func (response GetPlaylist404JSONResponse) VisitGetPlaylistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetPlaylist500JSONResponse Error

func (response GetPlaylist500JSONResponse) VisitGetPlaylistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdatePlaylistRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdatePlaylistJSONRequestBody
}

type UpdatePlaylistResponseObject interface {
	VisitUpdatePlaylistResponse(w http.ResponseWriter) error
}

type UpdatePlaylist204Response struct {
}

func (response UpdatePlaylist204Response) VisitUpdatePlaylistResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdatePlaylist400JSONResponse Error

func (response UpdatePlaylist400JSONResponse) VisitUpdatePlaylistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdatePlaylist404JSONResponse Error

func (response UpdatePlaylist404JSONResponse) VisitUpdatePlaylistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdatePlaylist500JSONResponse Error

func (response UpdatePlaylist500JSONResponse) VisitUpdatePlaylistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RemoveSongFromPlaylistRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *RemoveSongFromPlaylistJSONRequestBody
}

type RemoveSongFromPlaylistResponseObject interface {
	VisitRemoveSongFromPlaylistResponse(w http.ResponseWriter) error
}

type RemoveSongFromPlaylist204Response struct {
}

func (response RemoveSongFromPlaylist204Response) VisitRemoveSongFromPlaylistResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RemoveSongFromPlaylist400JSONResponse Error

func (response RemoveSongFromPlaylist400JSONResponse) VisitRemoveSongFromPlaylistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RemoveSongFromPlaylist404JSONResponse Error

func (response RemoveSongFromPlaylist404JSONResponse) VisitRemoveSongFromPlaylistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RemoveSongFromPlaylist500JSONResponse Error

func (response RemoveSongFromPlaylist500JSONResponse) VisitRemoveSongFromPlaylistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetPlaylistSongsRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetPlaylistSongsResponseObject interface {
	VisitGetPlaylistSongsResponse(w http.ResponseWriter) error
}

type GetPlaylistSongs200JSONResponse SongList

func (response GetPlaylistSongs200JSONResponse) VisitGetPlaylistSongsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPlaylistSongs404JSONResponse Error

func (response GetPlaylistSongs404JSONResponse) VisitGetPlaylistSongsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetPlaylistSongs500JSONResponse Error

func (response GetPlaylistSongs500JSONResponse) VisitGetPlaylistSongsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddSongToPlaylistRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *AddSongToPlaylistJSONRequestBody
}

type AddSongToPlaylistResponseObject interface {
	VisitAddSongToPlaylistResponse(w http.ResponseWriter) error
}

type AddSongToPlaylist204Response struct {
}

func (response AddSongToPlaylist204Response) VisitAddSongToPlaylistResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type AddSongToPlaylist400JSONResponse Error

func (response AddSongToPlaylist400JSONResponse) VisitAddSongToPlaylistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddSongToPlaylist404JSONResponse Error

func (response AddSongToPlaylist404JSONResponse) VisitAddSongToPlaylistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AddSongToPlaylist500JSONResponse Error

func (response AddSongToPlaylist500JSONResponse) VisitAddSongToPlaylistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetReleaseRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetReleaseResponseObject interface {
	VisitGetReleaseResponse(w http.ResponseWriter) error
}

type GetRelease200JSONResponse Release

func (response GetRelease200JSONResponse) VisitGetReleaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRelease404JSONResponse Error

func (response GetRelease404JSONResponse) VisitGetReleaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetRelease500JSONResponse Error

func (response GetRelease500JSONResponse) VisitGetReleaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSongRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetSongResponseObject interface {
	VisitGetSongResponse(w http.ResponseWriter) error
}

type GetSong200JSONResponse Song

func (response GetSong200JSONResponse) VisitGetSongResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSong404JSONResponse Error

func (response GetSong404JSONResponse) VisitGetSongResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSong500JSONResponse Error

func (response GetSong500JSONResponse) VisitGetSongResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GenerateTokensRequestObject struct {
	Body *GenerateTokensJSONRequestBody
}

type GenerateTokensResponseObject interface {
	VisitGenerateTokensResponse(w http.ResponseWriter) error
}

type GenerateTokens200JSONResponse TokensResponse

func (response GenerateTokens200JSONResponse) VisitGenerateTokensResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GenerateTokens400JSONResponse Error

func (response GenerateTokens400JSONResponse) VisitGenerateTokensResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GenerateTokens500JSONResponse Error

func (response GenerateTokens500JSONResponse) VisitGenerateTokensResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

type CreateUser201JSONResponse User

func (response CreateUser201JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser400JSONResponse Error

func (response CreateUser400JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser409JSONResponse Error

func (response CreateUser409JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser500JSONResponse Error

func (response CreateUser500JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(w http.ResponseWriter) error
}

type GetCurrentUser200JSONResponse CurrentUser

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUser401JSONResponse Error

func (response GetCurrentUser401JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUser500JSONResponse Error

func (response GetCurrentUser500JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type SendVerificationEmailRequestObject struct {
	Body *SendVerificationEmailJSONRequestBody
}

type SendVerificationEmailResponseObject interface {
	VisitSendVerificationEmailResponse(w http.ResponseWriter) error
}

type SendVerificationEmail204Response struct {
}

func (response SendVerificationEmail204Response) VisitSendVerificationEmailResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SendVerificationEmail400JSONResponse Error

func (response SendVerificationEmail400JSONResponse) VisitSendVerificationEmailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SendVerificationEmail429JSONResponse Error

func (response SendVerificationEmail429JSONResponse) VisitSendVerificationEmailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type SendVerificationEmail500JSONResponse Error

func (response SendVerificationEmail500JSONResponse) VisitSendVerificationEmailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get artist by ID
	// (GET /artists/{id})
	GetArtist(ctx context.Context, request GetArtistRequestObject) (GetArtistResponseObject, error)
	// Remove song from favorites
	// (DELETE /favorites)
	RemoveFavorite(ctx context.Context, request RemoveFavoriteRequestObject) (RemoveFavoriteResponseObject, error)
	// Get favorite songs
	// (GET /favorites)
	GetFavorites(ctx context.Context, request GetFavoritesRequestObject) (GetFavoritesResponseObject, error)
	// Add song to favorites
	// (POST /favorites)
	AddFavorite(ctx context.Context, request AddFavoriteRequestObject) (AddFavoriteResponseObject, error)
	// Unfollow an artist
	// (DELETE /followings)
	UnfollowArtist(ctx context.Context, request UnfollowArtistRequestObject) (UnfollowArtistResponseObject, error)
	// Get followed artists
	// (GET /followings)
	GetFollowings(ctx context.Context, request GetFollowingsRequestObject) (GetFollowingsResponseObject, error)
	// Follow an artist
	// (POST /followings)
	FollowArtist(ctx context.Context, request FollowArtistRequestObject) (FollowArtistResponseObject, error)
	// Get media file
	// (GET /media/{id})
	GetMedia(ctx context.Context, request GetMediaRequestObject) (GetMediaResponseObject, error)
	// Get a list of playlists
	// (GET /playlists)
	GetPlaylists(ctx context.Context, request GetPlaylistsRequestObject) (GetPlaylistsResponseObject, error)
	// Create a new playlist
	// (POST /playlists)
	CreatePlaylist(ctx context.Context, request CreatePlaylistRequestObject) (CreatePlaylistResponseObject, error)
	// Delete a playlist
	// (DELETE /playlists/{id})
	DeletePlaylist(ctx context.Context, request DeletePlaylistRequestObject) (DeletePlaylistResponseObject, error)
	// Get playlist by ID
	// (GET /playlists/{id})
	GetPlaylist(ctx context.Context, request GetPlaylistRequestObject) (GetPlaylistResponseObject, error)
	// Update a playlist
	// (PUT /playlists/{id})
	UpdatePlaylist(ctx context.Context, request UpdatePlaylistRequestObject) (UpdatePlaylistResponseObject, error)
	// Remove song from playlist
	// (DELETE /playlists/{id}/songs)
	RemoveSongFromPlaylist(ctx context.Context, request RemoveSongFromPlaylistRequestObject) (RemoveSongFromPlaylistResponseObject, error)
	// Get playlist songs
	// (GET /playlists/{id}/songs)
	GetPlaylistSongs(ctx context.Context, request GetPlaylistSongsRequestObject) (GetPlaylistSongsResponseObject, error)
	// Add song to playlist
	// (POST /playlists/{id}/songs)
	AddSongToPlaylist(ctx context.Context, request AddSongToPlaylistRequestObject) (AddSongToPlaylistResponseObject, error)
	// Get release by ID
	// (GET /releases/{id})
	GetRelease(ctx context.Context, request GetReleaseRequestObject) (GetReleaseResponseObject, error)
	// Get song by ID
	// (GET /songs/{id})
	GetSong(ctx context.Context, request GetSongRequestObject) (GetSongResponseObject, error)
	// Obtain access and refresh tokens
	// (POST /tokens)
	GenerateTokens(ctx context.Context, request GenerateTokensRequestObject) (GenerateTokensResponseObject, error)
	// Create user with verification code
	// (POST /users)
	CreateUser(ctx context.Context, request CreateUserRequestObject) (CreateUserResponseObject, error)
	// Get current authenticated user
	// (GET /users/me)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)
	// Send verification email
	// (POST /verification-email)
	SendVerificationEmail(ctx context.Context, request SendVerificationEmailRequestObject) (SendVerificationEmailResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetArtist operation middleware
func (sh *strictHandler) GetArtist(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetArtistRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetArtist(ctx, request.(GetArtistRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetArtist")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetArtistResponseObject); ok {
		if err := validResponse.VisitGetArtistResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RemoveFavorite operation middleware
func (sh *strictHandler) RemoveFavorite(w http.ResponseWriter, r *http.Request) {
	var request RemoveFavoriteRequestObject

	var body RemoveFavoriteJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RemoveFavorite(ctx, request.(RemoveFavoriteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RemoveFavorite")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RemoveFavoriteResponseObject); ok {
		if err := validResponse.VisitRemoveFavoriteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFavorites operation middleware
func (sh *strictHandler) GetFavorites(w http.ResponseWriter, r *http.Request) {
	var request GetFavoritesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFavorites(ctx, request.(GetFavoritesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFavorites")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFavoritesResponseObject); ok {
		if err := validResponse.VisitGetFavoritesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddFavorite operation middleware
func (sh *strictHandler) AddFavorite(w http.ResponseWriter, r *http.Request) {
	var request AddFavoriteRequestObject

	var body AddFavoriteJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddFavorite(ctx, request.(AddFavoriteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddFavorite")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddFavoriteResponseObject); ok {
		if err := validResponse.VisitAddFavoriteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UnfollowArtist operation middleware
func (sh *strictHandler) UnfollowArtist(w http.ResponseWriter, r *http.Request) {
	var request UnfollowArtistRequestObject

	var body UnfollowArtistJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UnfollowArtist(ctx, request.(UnfollowArtistRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UnfollowArtist")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UnfollowArtistResponseObject); ok {
		if err := validResponse.VisitUnfollowArtistResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFollowings operation middleware
func (sh *strictHandler) GetFollowings(w http.ResponseWriter, r *http.Request) {
	var request GetFollowingsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFollowings(ctx, request.(GetFollowingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFollowings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFollowingsResponseObject); ok {
		if err := validResponse.VisitGetFollowingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// FollowArtist operation middleware
func (sh *strictHandler) FollowArtist(w http.ResponseWriter, r *http.Request) {
	var request FollowArtistRequestObject

	var body FollowArtistJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FollowArtist(ctx, request.(FollowArtistRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FollowArtist")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FollowArtistResponseObject); ok {
		if err := validResponse.VisitFollowArtistResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMedia operation middleware
func (sh *strictHandler) GetMedia(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetMediaRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMedia(ctx, request.(GetMediaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMedia")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMediaResponseObject); ok {
		if err := validResponse.VisitGetMediaResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPlaylists operation middleware
func (sh *strictHandler) GetPlaylists(w http.ResponseWriter, r *http.Request) {
	var request GetPlaylistsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPlaylists(ctx, request.(GetPlaylistsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPlaylists")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPlaylistsResponseObject); ok {
		if err := validResponse.VisitGetPlaylistsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePlaylist operation middleware
func (sh *strictHandler) CreatePlaylist(w http.ResponseWriter, r *http.Request) {
	var request CreatePlaylistRequestObject

	var body CreatePlaylistJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePlaylist(ctx, request.(CreatePlaylistRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePlaylist")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePlaylistResponseObject); ok {
		if err := validResponse.VisitCreatePlaylistResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeletePlaylist operation middleware
func (sh *strictHandler) DeletePlaylist(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeletePlaylistRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeletePlaylist(ctx, request.(DeletePlaylistRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeletePlaylist")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeletePlaylistResponseObject); ok {
		if err := validResponse.VisitDeletePlaylistResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPlaylist operation middleware
func (sh *strictHandler) GetPlaylist(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetPlaylistRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPlaylist(ctx, request.(GetPlaylistRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPlaylist")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPlaylistResponseObject); ok {
		if err := validResponse.VisitGetPlaylistResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdatePlaylist operation middleware
func (sh *strictHandler) UpdatePlaylist(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdatePlaylistRequestObject

	request.Id = id

	var body UpdatePlaylistJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdatePlaylist(ctx, request.(UpdatePlaylistRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdatePlaylist")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdatePlaylistResponseObject); ok {
		if err := validResponse.VisitUpdatePlaylistResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RemoveSongFromPlaylist operation middleware
func (sh *strictHandler) RemoveSongFromPlaylist(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request RemoveSongFromPlaylistRequestObject

	request.Id = id

	var body RemoveSongFromPlaylistJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RemoveSongFromPlaylist(ctx, request.(RemoveSongFromPlaylistRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RemoveSongFromPlaylist")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RemoveSongFromPlaylistResponseObject); ok {
		if err := validResponse.VisitRemoveSongFromPlaylistResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPlaylistSongs operation middleware
func (sh *strictHandler) GetPlaylistSongs(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetPlaylistSongsRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPlaylistSongs(ctx, request.(GetPlaylistSongsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPlaylistSongs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPlaylistSongsResponseObject); ok {
		if err := validResponse.VisitGetPlaylistSongsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddSongToPlaylist operation middleware
func (sh *strictHandler) AddSongToPlaylist(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request AddSongToPlaylistRequestObject

	request.Id = id

	var body AddSongToPlaylistJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddSongToPlaylist(ctx, request.(AddSongToPlaylistRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddSongToPlaylist")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddSongToPlaylistResponseObject); ok {
		if err := validResponse.VisitAddSongToPlaylistResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRelease operation middleware
func (sh *strictHandler) GetRelease(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetReleaseRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRelease(ctx, request.(GetReleaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRelease")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReleaseResponseObject); ok {
		if err := validResponse.VisitGetReleaseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSong operation middleware
func (sh *strictHandler) GetSong(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetSongRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSong(ctx, request.(GetSongRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSong")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSongResponseObject); ok {
		if err := validResponse.VisitGetSongResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GenerateTokens operation middleware
func (sh *strictHandler) GenerateTokens(w http.ResponseWriter, r *http.Request) {
	var request GenerateTokensRequestObject

	var body GenerateTokensJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GenerateTokens(ctx, request.(GenerateTokensRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GenerateTokens")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GenerateTokensResponseObject); ok {
		if err := validResponse.VisitGenerateTokensResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateUser operation middleware
func (sh *strictHandler) CreateUser(w http.ResponseWriter, r *http.Request) {
	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUser(ctx, request.(CreateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateUserResponseObject); ok {
		if err := validResponse.VisitCreateUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	var request GetCurrentUserRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx, request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		if err := validResponse.VisitGetCurrentUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SendVerificationEmail operation middleware
func (sh *strictHandler) SendVerificationEmail(w http.ResponseWriter, r *http.Request) {
	var request SendVerificationEmailRequestObject

	var body SendVerificationEmailJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SendVerificationEmail(ctx, request.(SendVerificationEmailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SendVerificationEmail")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SendVerificationEmailResponseObject); ok {
		if err := validResponse.VisitSendVerificationEmailResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
