name: Deploy Docker Compose to Server

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["docker-push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker context
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Set up SSH for Docker context
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create Docker context on GitHub runner
        run: |
          docker context create my-swarm --docker "host=ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}"
          docker context use my-swarm

      - name: Deploy to Docker Swarm
        run: |
          docker context use my-swarm
          
          export MAILGUN_API_KEY="${{ secrets.MAILGUN_API_KEY }}"
          export MAILGUN_FROM="${{ secrets.MAILGUN_FROM }}"
          export MAILGUN_DOMAIN="${{ secrets.MAILGUN_DOMAIN }}"
          export JWT_SECRET="${{ secrets.JWT_SECRET }}"
          export GOOGLE_AUTH_AUDIENCE="${{ secrets.GOOGLE_AUTH_AUDIENCE }}"
          
          docker stack deploy -c docker-compose.yml your-stack-name
